;
; File generated by cc65 v 2.16 - Ubuntu 2.16-2
;
	.fopt		compiler,"cc65 v 2.16 - Ubuntu 2.16-2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_oam_buffer_spr
	.export		_paddle_draw
	.import		_match
	.export		_paddle_move_up2

; ---------------------------------------------------------------
; void __near__ paddle_draw (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_paddle_draw: near

.segment	"CODE"

;
; void paddle_draw(u8 n) {
;
	jsr     pusha
;
; if (n == 0) {
;
	ldy     #$00
	lda     (sp),y
	bne     L0018
;
; oam_buffer_spr(match.paddle[0].pos.x, match.paddle[0].pos.y, PADDLE_SPR1_ON, 0, PADDLE_SPR_1_1_NUM);
;
	jsr     decsp4
	lda     _match
	ldy     #$03
	sta     (sp),y
	lda     _match+1
	dey
	sta     (sp),y
	tya
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	lda     #$02
	jsr     _oam_buffer_spr
;
; oam_buffer_spr(match.paddle[0].pos.x, match.paddle[0].pos.y + 8, PADDLE_SPR1_ON, 0, PADDLE_SPR_1_2_NUM);
;
	jsr     decsp4
	lda     _match
	ldy     #$03
	sta     (sp),y
	lda     _match+1
	clc
	adc     #$08
	dey
	sta     (sp),y
	tya
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	lda     #$03
;
; } else {
;
	jmp     L004C
;
; oam_buffer_spr(match.paddle[1].pos.x, match.paddle[1].pos.y, PADDLE_SPR2_ON, 0, PADDLE_SPR_2_1_NUM);
;
L0018:	jsr     decsp4
	lda     _match+4
	ldy     #$03
	sta     (sp),y
	lda     _match+5
	dey
	sta     (sp),y
	lda     #$03
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	lda     #$04
	jsr     _oam_buffer_spr
;
; oam_buffer_spr(match.paddle[1].pos.x, match.paddle[1].pos.y + 8, PADDLE_SPR2_ON, 0, PADDLE_SPR_2_2_NUM);
;
	jsr     decsp4
	lda     _match+4
	ldy     #$03
	sta     (sp),y
	lda     _match+5
	clc
	adc     #$08
	dey
	sta     (sp),y
	lda     #$03
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	lda     #$05
L004C:	jsr     _oam_buffer_spr
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ paddle_move_up2 (__near__ struct $anon-struct-0008 *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_paddle_move_up2: near

.segment	"CODE"

;
; void paddle_move_up2(paddle_t *paddle) {
;
	jsr     pushax
;
; if (paddle->pos.y > PF_TOP + PADDLE_SPEED) {
;
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	iny
	lda     (ptr1),y
	cmp     #$13
	bcc     L0044
;
; paddle->pos.y -= PADDLE_SPEED;
;
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	iny
	lda     (ptr1),y
	sec
	sbc     #$02
	sta     (ptr1),y
;
; paddle->direction = -1;
;
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$FF
	ldy     #$03
	sta     (ptr1),y
;
; paddle_draw(paddle->num);
;
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$02
	lda     (ptr1),y
	jsr     _paddle_draw
;
; }
;
L0044:	jmp     incsp2

.endproc

